M48
; DRILL file {KiCad (6.0.2-0)} date Monday, 07 March 2022 at 07:25:34
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-07T07:25:34+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1220
%
G90
G05
T1
X3.1693Y-4.626
X3.1693Y-5.8858
X4.7244Y-4.626
X4.7244Y-5.8858
T0
M30
